/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe + version banner */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk meta for all tasks (used by sidebar) */
        get: operations["listTasksMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch: operations["updateTask"];
        trace?: never;
    };
    "/api/tasks/{id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["spawnTaskAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clearTaskRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["continueTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/detect/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshTaskDetect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        /** SSE — `task.event`, `agent.detect.progress` */
        get: operations["taskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-register coordinator/sub-agent session (uses x-bridge-internal-token) */
        post: operations["linkTaskSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get: operations["getTaskMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/runs/{sessionId}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get: operations["getRunDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/runs/{sessionId}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["killRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/runs/{sessionId}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get: operations["getRunPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get: operations["getTaskSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        get: operations["getTaskUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAllSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["killSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/permission": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get: operations["listSessionPermissions"];
        put?: never;
        post: operations["createSessionPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/permission/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
                requestId: components["parameters"]["RequestIdPath"];
            };
            cookie?: never;
        };
        get: operations["getSessionPermission"];
        put?: never;
        post: operations["decideSessionPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/permission/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        /** SSE — `permission.request` */
        get: operations["sessionPermissionStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/rewind": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rewindSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/tail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get: operations["getSessionTail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/tail/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        /** SSE — `session.tail` */
        get: operations["sessionTailStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadSessionFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApps"];
        put?: never;
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/auto-detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["autoDetectApps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/auto-detect/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE — `agent.detect.progress` */
        get: operations["autoDetectAppsStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkUpsertApps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        patch: operations["updateApp"];
        trace?: never;
    };
    "/api/apps/{name}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["getAppMemory"];
        put?: never;
        post: operations["writeAppMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{name}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scanApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepoProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/profiles/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshRepoProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["getRepoProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["listRepoFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{name}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["getRepoRaw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{name}/slash-commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["listRepoSlashCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/pending/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PendingLoginIdPath"];
            };
            cookie?: never;
        };
        get: operations["getPendingLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setupAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTunnels"];
        put?: never;
        post: operations["createTunnel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TunnelIdPath"];
            };
            cookie?: never;
        };
        get: operations["getTunnel"];
        put?: never;
        post?: never;
        delete: operations["deleteTunnel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnels/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTunnelProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnels/providers/ngrok/authtoken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setNgrokAuthtoken"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnels/providers/ngrok/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["installNgrok"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTelegramSettings"];
        put: operations["updateTelegramSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTelegramUserSettings"];
        put: operations["updateTelegramUserSettings"];
        post?: never;
        delete: operations["clearTelegramUserSettings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/user/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testTelegramUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect/scan-roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScanRoots"];
        put: operations["updateScanRoots"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetectSettings"];
        put: operations["updateDetectSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bridge/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBridgeSettings"];
        put: operations["updateBridgeSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permission/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE — `permission.request` */
        get: operations["permissionStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{sessionId}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
                name: components["parameters"]["UploadNamePath"];
            };
            cookie?: never;
        };
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error: string;
            code?: string | null;
            details?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description v0.1 placeholder for any successful JSON body. Per-domain sessions
         *     replace this with a concrete schema in `components/schemas`.
         */
        OkResponse: {
            [key: string]: unknown;
        };
        /** @description Placeholder schema while v0.1 is being filled in. */
        AnyJson: {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Success (v0.1 placeholder body) */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OkResponse"];
            };
        };
        /** @description Success with no body */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Server-Sent Events stream (`text/event-stream`) */
        Stream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/event-stream": string;
            };
        };
    };
    parameters: {
        TaskIdPath: string;
        SessionIdPath: string;
        NamePath: string;
        ApprovalIdPath: string;
        PendingLoginIdPath: string;
        RequestIdPath: string;
        TunnelIdPath: string;
        UploadNamePath: string;
    };
    requestBodies: {
        /** @description Generic JSON body (v0.1 placeholder) */
        Json: {
            content: {
                "application/json": components["schemas"]["AnyJson"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        version?: string;
                        /** @description Seconds since process start */
                        uptime?: number;
                    };
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            201: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listTasksMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    spawnTaskAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    clearTaskRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    continueTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    refreshTaskDetect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    taskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Stream"];
            default: components["responses"]["Error"];
        };
    };
    linkTaskSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getTaskMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getRunDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    killRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getRunPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getTaskSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plain markdown summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTaskUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    killSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    sendSessionMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listSessionPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    createSessionPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getSessionPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
                requestId: components["parameters"]["RequestIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    decideSessionPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
                requestId: components["parameters"]["RequestIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    sessionPermissionStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Stream"];
            default: components["responses"]["Error"];
        };
    };
    rewindSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getSessionTail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    sessionTailStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Stream"];
            default: components["responses"]["Error"];
        };
    };
    uploadSessionFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            201: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    autoDetectApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    autoDetectAppsStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Stream"];
            default: components["responses"]["Error"];
        };
    };
    bulkUpsertApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getAppMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    writeAppMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    scanApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listRepoProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    refreshRepoProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getRepoProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listRepoFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getRepoRaw: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw file content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRepoSlashCommands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalIdPath"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getPendingLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PendingLoginIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    setupAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listTunnels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    createTunnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            201: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getTunnel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TunnelIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    deleteTunnel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TunnelIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    listTunnelProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    setNgrokAuthtoken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    installNgrok: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getTelegramSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    updateTelegramSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    testTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getTelegramUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    updateTelegramUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    clearTelegramUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    testTelegramUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getScanRoots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    updateScanRoots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getDetectSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    updateDetectSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getBridgeSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    updateBridgeSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["Json"];
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    permissionStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Stream"];
            default: components["responses"]["Error"];
        };
    };
    getUsage: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            default: components["responses"]["Error"];
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionIdPath"];
                name: components["parameters"]["UploadNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw upload content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
