// Package genapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
//
// REGEN OUTPUT NOW: internal/api/genapi/openapi_gen.go
// Regen invocation (kept verbatim from docs/archive/MIGRATION_GO.md, with
// the new path):
//
//	oapi-codegen -generate types,chi-server -package genapi \
//	    api/openapi.yaml > internal/api/genapi/openapi_gen.go
package genapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	GetHealth200JSONResponseBodyStatusOk GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case GetHealth200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// AnyJson Placeholder schema while v0.1 is being filled in.
type AnyJson map[string]interface{}

// ApiError defines model for ApiError.
type ApiError struct {
	Code                 *string                 `json:"code,omitempty"`
	Details              *map[string]interface{} `json:"details,omitempty"`
	Error                string                  `json:"error"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// OkResponse v0.1 placeholder for any successful JSON body. Per-domain sessions
// replace this with a concrete schema in `components/schemas`.
type OkResponse map[string]interface{}

// ApprovalIdPath defines model for ApprovalIdPath.
type ApprovalIdPath = string

// NamePath defines model for NamePath.
type NamePath = string

// PendingLoginIdPath defines model for PendingLoginIdPath.
type PendingLoginIdPath = string

// RequestIdPath defines model for RequestIdPath.
type RequestIdPath = string

// SessionIdPath Claude Code session UUID.
type SessionIdPath = string

// TaskIdPath Task ID, format `t_YYYYMMDD_NNN`.
type TaskIdPath = string

// TunnelIdPath defines model for TunnelIdPath.
type TunnelIdPath = string

// UploadNamePath defines model for UploadNamePath.
type UploadNamePath = string

// Error defines model for Error.
type Error = ApiError

// Ok v0.1 placeholder for any successful JSON body. Per-domain sessions
// replace this with a concrete schema in `components/schemas`.
type Ok = OkResponse

// Json Placeholder schema while v0.1 is being filled in.
type Json = AnyJson

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// GetRepoRawParams defines parameters for GetRepoRaw.
type GetRepoRawParams struct {
	Path string `form:"path" json:"path"`
}

// UploadSessionFileMultipartBody defines parameters for UploadSessionFile.
type UploadSessionFileMultipartBody map[string]interface{}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	Range *string `form:"range,omitempty" json:"range,omitempty"`
}

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody = AnyJson

// BulkUpsertAppsJSONRequestBody defines body for BulkUpsertApps for application/json ContentType.
type BulkUpsertAppsJSONRequestBody = AnyJson

// UpdateAppJSONRequestBody defines body for UpdateApp for application/json ContentType.
type UpdateAppJSONRequestBody = AnyJson

// WriteAppMemoryJSONRequestBody defines body for WriteAppMemory for application/json ContentType.
type WriteAppMemoryJSONRequestBody = AnyJson

// ScanAppJSONRequestBody defines body for ScanApp for application/json ContentType.
type ScanAppJSONRequestBody = AnyJson

// DecideApprovalJSONRequestBody defines body for DecideApproval for application/json ContentType.
type DecideApprovalJSONRequestBody = AnyJson

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AnyJson

// SetupAuthJSONRequestBody defines body for SetupAuth for application/json ContentType.
type SetupAuthJSONRequestBody = AnyJson

// UpdateBridgeSettingsJSONRequestBody defines body for UpdateBridgeSettings for application/json ContentType.
type UpdateBridgeSettingsJSONRequestBody = AnyJson

// UpdateScanRootsJSONRequestBody defines body for UpdateScanRoots for application/json ContentType.
type UpdateScanRootsJSONRequestBody = AnyJson

// UpdateDetectSettingsJSONRequestBody defines body for UpdateDetectSettings for application/json ContentType.
type UpdateDetectSettingsJSONRequestBody = AnyJson

// RefreshRepoProfilesJSONRequestBody defines body for RefreshRepoProfiles for application/json ContentType.
type RefreshRepoProfilesJSONRequestBody = AnyJson

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = AnyJson

// SendSessionMessageJSONRequestBody defines body for SendSessionMessage for application/json ContentType.
type SendSessionMessageJSONRequestBody = AnyJson

// CreateSessionPermissionJSONRequestBody defines body for CreateSessionPermission for application/json ContentType.
type CreateSessionPermissionJSONRequestBody = AnyJson

// DecideSessionPermissionJSONRequestBody defines body for DecideSessionPermission for application/json ContentType.
type DecideSessionPermissionJSONRequestBody = AnyJson

// RewindSessionJSONRequestBody defines body for RewindSession for application/json ContentType.
type RewindSessionJSONRequestBody = AnyJson

// UploadSessionFileMultipartRequestBody defines body for UploadSessionFile for multipart/form-data ContentType.
type UploadSessionFileMultipartRequestBody UploadSessionFileMultipartBody

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = AnyJson

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = AnyJson

// SpawnTaskAgentJSONRequestBody defines body for SpawnTaskAgent for application/json ContentType.
type SpawnTaskAgentJSONRequestBody = AnyJson

// ContinueTaskJSONRequestBody defines body for ContinueTask for application/json ContentType.
type ContinueTaskJSONRequestBody = AnyJson

// LinkTaskSessionJSONRequestBody defines body for LinkTaskSession for application/json ContentType.
type LinkTaskSessionJSONRequestBody = AnyJson

// UpdateTelegramSettingsJSONRequestBody defines body for UpdateTelegramSettings for application/json ContentType.
type UpdateTelegramSettingsJSONRequestBody = AnyJson

// UpdateTelegramUserSettingsJSONRequestBody defines body for UpdateTelegramUserSettings for application/json ContentType.
type UpdateTelegramUserSettingsJSONRequestBody = AnyJson

// TestTelegramUserJSONRequestBody defines body for TestTelegramUser for application/json ContentType.
type TestTelegramUserJSONRequestBody = AnyJson

// CreateTunnelJSONRequestBody defines body for CreateTunnel for application/json ContentType.
type CreateTunnelJSONRequestBody = AnyJson

// SetNgrokAuthtokenJSONRequestBody defines body for SetNgrokAuthtoken for application/json ContentType.
type SetNgrokAuthtokenJSONRequestBody = AnyJson

// InstallNgrokJSONRequestBody defines body for InstallNgrok for application/json ContentType.
type InstallNgrokJSONRequestBody = AnyJson

// Getter for additional properties for ApiError. Returns the specified
// element and whether it was found
func (a ApiError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ApiError
func (a *ApiError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ApiError to handle AdditionalProperties
func (a *ApiError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["details"]; found {
		err = json.Unmarshal(raw, &a.Details)
		if err != nil {
			return fmt.Errorf("error reading 'details': %w", err)
		}
		delete(object, "details")
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ApiError to handle AdditionalProperties
func (a ApiError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Details != nil {
		object["details"], err = json.Marshal(a.Details)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'details': %w", err)
		}
	}

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/apps)
	ListApps(w http.ResponseWriter, r *http.Request)

	// (POST /api/apps)
	CreateApp(w http.ResponseWriter, r *http.Request)

	// (POST /api/apps/auto-detect)
	AutoDetectApps(w http.ResponseWriter, r *http.Request)
	// SSE — `agent.detect.progress`
	// (GET /api/apps/auto-detect/stream)
	AutoDetectAppsStream(w http.ResponseWriter, r *http.Request)

	// (POST /api/apps/bulk)
	BulkUpsertApps(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/apps/{name})
	DeleteApp(w http.ResponseWriter, r *http.Request, name NamePath)

	// (PATCH /api/apps/{name})
	UpdateApp(w http.ResponseWriter, r *http.Request, name NamePath)

	// (GET /api/apps/{name}/memory)
	GetAppMemory(w http.ResponseWriter, r *http.Request, name NamePath)

	// (POST /api/apps/{name}/memory)
	WriteAppMemory(w http.ResponseWriter, r *http.Request, name NamePath)

	// (POST /api/apps/{name}/scan)
	ScanApp(w http.ResponseWriter, r *http.Request, name NamePath)

	// (GET /api/auth/approvals)
	ListApprovals(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/approvals/{id})
	DecideApproval(w http.ResponseWriter, r *http.Request, id ApprovalIdPath)

	// (DELETE /api/auth/devices)
	DeleteDevice(w http.ResponseWriter, r *http.Request)

	// (GET /api/auth/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (GET /api/auth/login/pending/{id})
	GetPendingLogin(w http.ResponseWriter, r *http.Request, id PendingLoginIdPath)

	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (GET /api/auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/setup)
	SetupAuth(w http.ResponseWriter, r *http.Request)

	// (GET /api/bridge/settings)
	GetBridgeSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/bridge/settings)
	UpdateBridgeSettings(w http.ResponseWriter, r *http.Request)

	// (GET /api/detect/scan-roots)
	GetScanRoots(w http.ResponseWriter, r *http.Request)

	// (PUT /api/detect/scan-roots)
	UpdateScanRoots(w http.ResponseWriter, r *http.Request)

	// (GET /api/detect/settings)
	GetDetectSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/detect/settings)
	UpdateDetectSettings(w http.ResponseWriter, r *http.Request)
	// Liveness probe + version banner
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/permission)
	ListPermissions(w http.ResponseWriter, r *http.Request)
	// SSE — `permission.request`
	// (GET /api/permission/stream)
	PermissionStream(w http.ResponseWriter, r *http.Request)

	// (GET /api/repos)
	ListRepos(w http.ResponseWriter, r *http.Request)

	// (GET /api/repos/profiles)
	ListRepoProfiles(w http.ResponseWriter, r *http.Request)

	// (POST /api/repos/profiles/refresh)
	RefreshRepoProfiles(w http.ResponseWriter, r *http.Request)

	// (GET /api/repos/profiles/{name})
	GetRepoProfile(w http.ResponseWriter, r *http.Request, name NamePath)

	// (GET /api/repos/{name}/files)
	ListRepoFiles(w http.ResponseWriter, r *http.Request, name NamePath)

	// (GET /api/repos/{name}/raw)
	GetRepoRaw(w http.ResponseWriter, r *http.Request, name NamePath, params GetRepoRawParams)

	// (GET /api/repos/{name}/slash-commands)
	ListRepoSlashCommands(w http.ResponseWriter, r *http.Request, name NamePath)

	// (POST /api/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)

	// (GET /api/sessions/all)
	ListAllSessions(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (POST /api/sessions/{sessionId}/kill)
	KillSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (POST /api/sessions/{sessionId}/message)
	SendSessionMessage(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (GET /api/sessions/{sessionId}/permission)
	ListSessionPermissions(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (POST /api/sessions/{sessionId}/permission)
	CreateSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)
	// SSE — `permission.request`
	// (GET /api/sessions/{sessionId}/permission/stream)
	SessionPermissionStream(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (GET /api/sessions/{sessionId}/permission/{requestId})
	GetSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, requestId RequestIdPath)

	// (POST /api/sessions/{sessionId}/permission/{requestId})
	DecideSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, requestId RequestIdPath)

	// (POST /api/sessions/{sessionId}/rewind)
	RewindSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (GET /api/sessions/{sessionId}/tail)
	GetSessionTail(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)
	// SSE — `session.tail`
	// (GET /api/sessions/{sessionId}/tail/stream)
	SessionTailStream(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (POST /api/sessions/{sessionId}/upload)
	UploadSessionFile(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath)

	// (GET /api/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request)

	// (POST /api/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// Bulk meta for all tasks (used by sidebar)
	// (GET /api/tasks/meta)
	ListTasksMeta(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/tasks/{id})
	DeleteTask(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (PATCH /api/tasks/{id})
	UpdateTask(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (POST /api/tasks/{id}/agents)
	SpawnTaskAgent(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (POST /api/tasks/{id}/clear)
	ClearTaskRuns(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (POST /api/tasks/{id}/continue)
	ContinueTask(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (POST /api/tasks/{id}/detect/refresh)
	RefreshTaskDetect(w http.ResponseWriter, r *http.Request, id TaskIdPath)
	// SSE — `task.event`, `agent.detect.progress`
	// (GET /api/tasks/{id}/events)
	TaskEvents(w http.ResponseWriter, r *http.Request, id TaskIdPath)
	// Self-register coordinator/sub-agent session (uses x-bridge-internal-token)
	// (POST /api/tasks/{id}/link)
	LinkTaskSession(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (GET /api/tasks/{id}/meta)
	GetTaskMeta(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (GET /api/tasks/{id}/runs/{sessionId}/diff)
	GetRunDiff(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath)

	// (POST /api/tasks/{id}/runs/{sessionId}/kill)
	KillRun(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath)

	// (GET /api/tasks/{id}/runs/{sessionId}/prompt)
	GetRunPrompt(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath)

	// (GET /api/tasks/{id}/summary)
	GetTaskSummary(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (GET /api/tasks/{id}/usage)
	GetTaskUsage(w http.ResponseWriter, r *http.Request, id TaskIdPath)

	// (GET /api/telegram/settings)
	GetTelegramSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/telegram/settings)
	UpdateTelegramSettings(w http.ResponseWriter, r *http.Request)

	// (POST /api/telegram/test)
	TestTelegram(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/telegram/user/settings)
	ClearTelegramUserSettings(w http.ResponseWriter, r *http.Request)

	// (GET /api/telegram/user/settings)
	GetTelegramUserSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/telegram/user/settings)
	UpdateTelegramUserSettings(w http.ResponseWriter, r *http.Request)

	// (POST /api/telegram/user/test)
	TestTelegramUser(w http.ResponseWriter, r *http.Request)

	// (GET /api/tunnels)
	ListTunnels(w http.ResponseWriter, r *http.Request)

	// (POST /api/tunnels)
	CreateTunnel(w http.ResponseWriter, r *http.Request)

	// (GET /api/tunnels/providers)
	ListTunnelProviders(w http.ResponseWriter, r *http.Request)

	// (PUT /api/tunnels/providers/ngrok/authtoken)
	SetNgrokAuthtoken(w http.ResponseWriter, r *http.Request)

	// (POST /api/tunnels/providers/ngrok/install)
	InstallNgrok(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/tunnels/{id})
	DeleteTunnel(w http.ResponseWriter, r *http.Request, id TunnelIdPath)

	// (GET /api/tunnels/{id})
	GetTunnel(w http.ResponseWriter, r *http.Request, id TunnelIdPath)

	// (GET /api/uploads/{sessionId}/{name})
	GetUpload(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, name UploadNamePath)

	// (GET /api/usage)
	GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/apps)
func (_ Unimplemented) ListApps(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/apps)
func (_ Unimplemented) CreateApp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/apps/auto-detect)
func (_ Unimplemented) AutoDetectApps(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE — `agent.detect.progress`
// (GET /api/apps/auto-detect/stream)
func (_ Unimplemented) AutoDetectAppsStream(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/apps/bulk)
func (_ Unimplemented) BulkUpsertApps(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/apps/{name})
func (_ Unimplemented) DeleteApp(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/apps/{name})
func (_ Unimplemented) UpdateApp(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/apps/{name}/memory)
func (_ Unimplemented) GetAppMemory(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/apps/{name}/memory)
func (_ Unimplemented) WriteAppMemory(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/apps/{name}/scan)
func (_ Unimplemented) ScanApp(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/auth/approvals)
func (_ Unimplemented) ListApprovals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/approvals/{id})
func (_ Unimplemented) DecideApproval(w http.ResponseWriter, r *http.Request, id ApprovalIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/auth/devices)
func (_ Unimplemented) DeleteDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/auth/devices)
func (_ Unimplemented) ListDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/auth/login/pending/{id})
func (_ Unimplemented) GetPendingLogin(w http.ResponseWriter, r *http.Request, id PendingLoginIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/setup)
func (_ Unimplemented) SetupAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/bridge/settings)
func (_ Unimplemented) GetBridgeSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/bridge/settings)
func (_ Unimplemented) UpdateBridgeSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/detect/scan-roots)
func (_ Unimplemented) GetScanRoots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/detect/scan-roots)
func (_ Unimplemented) UpdateScanRoots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/detect/settings)
func (_ Unimplemented) GetDetectSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/detect/settings)
func (_ Unimplemented) UpdateDetectSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe + version banner
// (GET /api/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/permission)
func (_ Unimplemented) ListPermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE — `permission.request`
// (GET /api/permission/stream)
func (_ Unimplemented) PermissionStream(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos)
func (_ Unimplemented) ListRepos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos/profiles)
func (_ Unimplemented) ListRepoProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/repos/profiles/refresh)
func (_ Unimplemented) RefreshRepoProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos/profiles/{name})
func (_ Unimplemented) GetRepoProfile(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos/{name}/files)
func (_ Unimplemented) ListRepoFiles(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos/{name}/raw)
func (_ Unimplemented) GetRepoRaw(w http.ResponseWriter, r *http.Request, name NamePath, params GetRepoRawParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/repos/{name}/slash-commands)
func (_ Unimplemented) ListRepoSlashCommands(w http.ResponseWriter, r *http.Request, name NamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions)
func (_ Unimplemented) CreateSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/all)
func (_ Unimplemented) ListAllSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/sessions/{sessionId})
func (_ Unimplemented) DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/kill)
func (_ Unimplemented) KillSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/message)
func (_ Unimplemented) SendSessionMessage(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{sessionId}/permission)
func (_ Unimplemented) ListSessionPermissions(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/permission)
func (_ Unimplemented) CreateSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE — `permission.request`
// (GET /api/sessions/{sessionId}/permission/stream)
func (_ Unimplemented) SessionPermissionStream(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{sessionId}/permission/{requestId})
func (_ Unimplemented) GetSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, requestId RequestIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/permission/{requestId})
func (_ Unimplemented) DecideSessionPermission(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, requestId RequestIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/rewind)
func (_ Unimplemented) RewindSession(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{sessionId}/tail)
func (_ Unimplemented) GetSessionTail(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE — `session.tail`
// (GET /api/sessions/{sessionId}/tail/stream)
func (_ Unimplemented) SessionTailStream(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{sessionId}/upload)
func (_ Unimplemented) UploadSessionFile(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk meta for all tasks (used by sidebar)
// (GET /api/tasks/meta)
func (_ Unimplemented) ListTasksMeta(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/tasks/{id})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api/tasks/{id})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks/{id}/agents)
func (_ Unimplemented) SpawnTaskAgent(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks/{id}/clear)
func (_ Unimplemented) ClearTaskRuns(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks/{id}/continue)
func (_ Unimplemented) ContinueTask(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks/{id}/detect/refresh)
func (_ Unimplemented) RefreshTaskDetect(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE — `task.event`, `agent.detect.progress`
// (GET /api/tasks/{id}/events)
func (_ Unimplemented) TaskEvents(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Self-register coordinator/sub-agent session (uses x-bridge-internal-token)
// (POST /api/tasks/{id}/link)
func (_ Unimplemented) LinkTaskSession(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks/{id}/meta)
func (_ Unimplemented) GetTaskMeta(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks/{id}/runs/{sessionId}/diff)
func (_ Unimplemented) GetRunDiff(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tasks/{id}/runs/{sessionId}/kill)
func (_ Unimplemented) KillRun(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks/{id}/runs/{sessionId}/prompt)
func (_ Unimplemented) GetRunPrompt(w http.ResponseWriter, r *http.Request, id TaskIdPath, sessionId SessionIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks/{id}/summary)
func (_ Unimplemented) GetTaskSummary(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tasks/{id}/usage)
func (_ Unimplemented) GetTaskUsage(w http.ResponseWriter, r *http.Request, id TaskIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/telegram/settings)
func (_ Unimplemented) GetTelegramSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/telegram/settings)
func (_ Unimplemented) UpdateTelegramSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/telegram/test)
func (_ Unimplemented) TestTelegram(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/telegram/user/settings)
func (_ Unimplemented) ClearTelegramUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/telegram/user/settings)
func (_ Unimplemented) GetTelegramUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/telegram/user/settings)
func (_ Unimplemented) UpdateTelegramUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/telegram/user/test)
func (_ Unimplemented) TestTelegramUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tunnels)
func (_ Unimplemented) ListTunnels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tunnels)
func (_ Unimplemented) CreateTunnel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tunnels/providers)
func (_ Unimplemented) ListTunnelProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/tunnels/providers/ngrok/authtoken)
func (_ Unimplemented) SetNgrokAuthtoken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/tunnels/providers/ngrok/install)
func (_ Unimplemented) InstallNgrok(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/tunnels/{id})
func (_ Unimplemented) DeleteTunnel(w http.ResponseWriter, r *http.Request, id TunnelIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/tunnels/{id})
func (_ Unimplemented) GetTunnel(w http.ResponseWriter, r *http.Request, id TunnelIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/uploads/{sessionId}/{name})
func (_ Unimplemented) GetUpload(w http.ResponseWriter, r *http.Request, sessionId SessionIdPath, name UploadNamePath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/usage)
func (_ Unimplemented) GetUsage(w http.ResponseWriter, r *http.Request, params GetUsageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApps operation middleware
func (siw *ServerInterfaceWrapper) ListApps(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApp operation middleware
func (siw *ServerInterfaceWrapper) CreateApp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AutoDetectApps operation middleware
func (siw *ServerInterfaceWrapper) AutoDetectApps(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AutoDetectApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AutoDetectAppsStream operation middleware
func (siw *ServerInterfaceWrapper) AutoDetectAppsStream(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AutoDetectAppsStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkUpsertApps operation middleware
func (siw *ServerInterfaceWrapper) BulkUpsertApps(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkUpsertApps(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApp operation middleware
func (siw *ServerInterfaceWrapper) DeleteApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApp(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApp operation middleware
func (siw *ServerInterfaceWrapper) UpdateApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApp(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAppMemory operation middleware
func (siw *ServerInterfaceWrapper) GetAppMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAppMemory(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WriteAppMemory operation middleware
func (siw *ServerInterfaceWrapper) WriteAppMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WriteAppMemory(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScanApp operation middleware
func (siw *ServerInterfaceWrapper) ScanApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScanApp(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApprovals operation middleware
func (siw *ServerInterfaceWrapper) ListApprovals(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApprovals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideApproval operation middleware
func (siw *ServerInterfaceWrapper) DecideApproval(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ApprovalIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideApproval(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPendingLogin operation middleware
func (siw *ServerInterfaceWrapper) GetPendingLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PendingLoginIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPendingLogin(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetupAuth operation middleware
func (siw *ServerInterfaceWrapper) SetupAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetupAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBridgeSettings operation middleware
func (siw *ServerInterfaceWrapper) GetBridgeSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBridgeSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBridgeSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateBridgeSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBridgeSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScanRoots operation middleware
func (siw *ServerInterfaceWrapper) GetScanRoots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScanRoots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateScanRoots operation middleware
func (siw *ServerInterfaceWrapper) UpdateScanRoots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateScanRoots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDetectSettings operation middleware
func (siw *ServerInterfaceWrapper) GetDetectSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDetectSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDetectSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateDetectSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDetectSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPermissions operation middleware
func (siw *ServerInterfaceWrapper) ListPermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PermissionStream operation middleware
func (siw *ServerInterfaceWrapper) PermissionStream(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PermissionStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepos operation middleware
func (siw *ServerInterfaceWrapper) ListRepos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListRepoProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshRepoProfiles operation middleware
func (siw *ServerInterfaceWrapper) RefreshRepoProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshRepoProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepoProfile operation middleware
func (siw *ServerInterfaceWrapper) GetRepoProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepoProfile(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoFiles operation middleware
func (siw *ServerInterfaceWrapper) ListRepoFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoFiles(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepoRaw operation middleware
func (siw *ServerInterfaceWrapper) GetRepoRaw(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRepoRawParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepoRaw(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepoSlashCommands operation middleware
func (siw *ServerInterfaceWrapper) ListRepoSlashCommands(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name NamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepoSlashCommands(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAllSessions operation middleware
func (siw *ServerInterfaceWrapper) ListAllSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAllSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KillSession operation middleware
func (siw *ServerInterfaceWrapper) KillSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KillSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendSessionMessage operation middleware
func (siw *ServerInterfaceWrapper) SendSessionMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendSessionMessage(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessionPermissions operation middleware
func (siw *ServerInterfaceWrapper) ListSessionPermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessionPermissions(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSessionPermission operation middleware
func (siw *ServerInterfaceWrapper) CreateSessionPermission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSessionPermission(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionPermissionStream operation middleware
func (siw *ServerInterfaceWrapper) SessionPermissionStream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionPermissionStream(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionPermission operation middleware
func (siw *ServerInterfaceWrapper) GetSessionPermission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "requestId" -------------
	var requestId RequestIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", chi.URLParam(r, "requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionPermission(w, r, sessionId, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideSessionPermission operation middleware
func (siw *ServerInterfaceWrapper) DecideSessionPermission(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "requestId" -------------
	var requestId RequestIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", chi.URLParam(r, "requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideSessionPermission(w, r, sessionId, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewindSession operation middleware
func (siw *ServerInterfaceWrapper) RewindSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewindSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionTail operation middleware
func (siw *ServerInterfaceWrapper) GetSessionTail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionTail(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionTailStream operation middleware
func (siw *ServerInterfaceWrapper) SessionTailStream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionTailStream(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSessionFile operation middleware
func (siw *ServerInterfaceWrapper) UploadSessionFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSessionFile(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasksMeta operation middleware
func (siw *ServerInterfaceWrapper) ListTasksMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasksMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SpawnTaskAgent operation middleware
func (siw *ServerInterfaceWrapper) SpawnTaskAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SpawnTaskAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearTaskRuns operation middleware
func (siw *ServerInterfaceWrapper) ClearTaskRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearTaskRuns(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueTask operation middleware
func (siw *ServerInterfaceWrapper) ContinueTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTaskDetect operation middleware
func (siw *ServerInterfaceWrapper) RefreshTaskDetect(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTaskDetect(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TaskEvents operation middleware
func (siw *ServerInterfaceWrapper) TaskEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TaskEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkTaskSession operation middleware
func (siw *ServerInterfaceWrapper) LinkTaskSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkTaskSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskMeta operation middleware
func (siw *ServerInterfaceWrapper) GetTaskMeta(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskMeta(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunDiff operation middleware
func (siw *ServerInterfaceWrapper) GetRunDiff(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunDiff(w, r, id, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KillRun operation middleware
func (siw *ServerInterfaceWrapper) KillRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KillRun(w, r, id, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunPrompt operation middleware
func (siw *ServerInterfaceWrapper) GetRunPrompt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunPrompt(w, r, id, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskSummary operation middleware
func (siw *ServerInterfaceWrapper) GetTaskSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskSummary(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskUsage operation middleware
func (siw *ServerInterfaceWrapper) GetTaskUsage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TaskIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskUsage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTelegramSettings operation middleware
func (siw *ServerInterfaceWrapper) GetTelegramSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTelegramSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTelegramSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateTelegramSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTelegramSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestTelegram operation middleware
func (siw *ServerInterfaceWrapper) TestTelegram(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestTelegram(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearTelegramUserSettings operation middleware
func (siw *ServerInterfaceWrapper) ClearTelegramUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearTelegramUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTelegramUserSettings operation middleware
func (siw *ServerInterfaceWrapper) GetTelegramUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTelegramUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTelegramUserSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateTelegramUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTelegramUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestTelegramUser operation middleware
func (siw *ServerInterfaceWrapper) TestTelegramUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestTelegramUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTunnels operation middleware
func (siw *ServerInterfaceWrapper) ListTunnels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTunnels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTunnel operation middleware
func (siw *ServerInterfaceWrapper) CreateTunnel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTunnel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTunnelProviders operation middleware
func (siw *ServerInterfaceWrapper) ListTunnelProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTunnelProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetNgrokAuthtoken operation middleware
func (siw *ServerInterfaceWrapper) SetNgrokAuthtoken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetNgrokAuthtoken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InstallNgrok operation middleware
func (siw *ServerInterfaceWrapper) InstallNgrok(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstallNgrok(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTunnel operation middleware
func (siw *ServerInterfaceWrapper) DeleteTunnel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TunnelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTunnel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTunnel operation middleware
func (siw *ServerInterfaceWrapper) GetTunnel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TunnelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTunnel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUpload operation middleware
func (siw *ServerInterfaceWrapper) GetUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name UploadNamePath

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpload(w, r, sessionId, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/apps", wrapper.ListApps)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/apps", wrapper.CreateApp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/apps/auto-detect", wrapper.AutoDetectApps)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/apps/auto-detect/stream", wrapper.AutoDetectAppsStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/apps/bulk", wrapper.BulkUpsertApps)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/apps/{name}", wrapper.DeleteApp)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/apps/{name}", wrapper.UpdateApp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/apps/{name}/memory", wrapper.GetAppMemory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/apps/{name}/memory", wrapper.WriteAppMemory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/apps/{name}/scan", wrapper.ScanApp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/approvals", wrapper.ListApprovals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/approvals/{id}", wrapper.DecideApproval)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/auth/devices", wrapper.DeleteDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/devices", wrapper.ListDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/login/pending/{id}", wrapper.GetPendingLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/setup", wrapper.SetupAuth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bridge/settings", wrapper.GetBridgeSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/bridge/settings", wrapper.UpdateBridgeSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/detect/scan-roots", wrapper.GetScanRoots)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/detect/scan-roots", wrapper.UpdateScanRoots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/detect/settings", wrapper.GetDetectSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/detect/settings", wrapper.UpdateDetectSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/permission", wrapper.ListPermissions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/permission/stream", wrapper.PermissionStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos", wrapper.ListRepos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos/profiles", wrapper.ListRepoProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/repos/profiles/refresh", wrapper.RefreshRepoProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos/profiles/{name}", wrapper.GetRepoProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos/{name}/files", wrapper.ListRepoFiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos/{name}/raw", wrapper.GetRepoRaw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/repos/{name}/slash-commands", wrapper.ListRepoSlashCommands)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions", wrapper.CreateSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/all", wrapper.ListAllSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/sessions/{sessionId}", wrapper.DeleteSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/kill", wrapper.KillSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/message", wrapper.SendSessionMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{sessionId}/permission", wrapper.ListSessionPermissions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/permission", wrapper.CreateSessionPermission)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{sessionId}/permission/stream", wrapper.SessionPermissionStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{sessionId}/permission/{requestId}", wrapper.GetSessionPermission)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/permission/{requestId}", wrapper.DecideSessionPermission)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/rewind", wrapper.RewindSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{sessionId}/tail", wrapper.GetSessionTail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{sessionId}/tail/stream", wrapper.SessionTailStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{sessionId}/upload", wrapper.UploadSessionFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/meta", wrapper.ListTasksMeta)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/tasks/{id}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/tasks/{id}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/agents", wrapper.SpawnTaskAgent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/clear", wrapper.ClearTaskRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/continue", wrapper.ContinueTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/detect/refresh", wrapper.RefreshTaskDetect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/events", wrapper.TaskEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/link", wrapper.LinkTaskSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/meta", wrapper.GetTaskMeta)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/runs/{sessionId}/diff", wrapper.GetRunDiff)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/{id}/runs/{sessionId}/kill", wrapper.KillRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/runs/{sessionId}/prompt", wrapper.GetRunPrompt)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/summary", wrapper.GetTaskSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tasks/{id}/usage", wrapper.GetTaskUsage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/telegram/settings", wrapper.GetTelegramSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/telegram/settings", wrapper.UpdateTelegramSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/telegram/test", wrapper.TestTelegram)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/telegram/user/settings", wrapper.ClearTelegramUserSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/telegram/user/settings", wrapper.GetTelegramUserSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/telegram/user/settings", wrapper.UpdateTelegramUserSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/telegram/user/test", wrapper.TestTelegramUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tunnels", wrapper.ListTunnels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tunnels", wrapper.CreateTunnel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tunnels/providers", wrapper.ListTunnelProviders)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/tunnels/providers/ngrok/authtoken", wrapper.SetNgrokAuthtoken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tunnels/providers/ngrok/install", wrapper.InstallNgrok)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/tunnels/{id}", wrapper.DeleteTunnel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/tunnels/{id}", wrapper.GetTunnel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/uploads/{sessionId}/{name}", wrapper.GetUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/usage", wrapper.GetUsage)
	})

	return r
}
