package detect

// Single bilingual tokenizer + stopword set used by every detector
// surface. Go port of libs/detect/tokenize.ts.
//
// Vietnamese support: we don't try real word segmentation (would need
// a dictionary). Instead we strip diacritics and split on whitespace
// — Vietnamese is written with spaces between syllables, so this
// gives us per-syllable tokens that match the heuristic's needs
// ("khóa học" → ["khoa", "hoc"] which can be matched against feature
// vocab).
//
// The bilingual stopword set covers the most common filler words in
// both languages so a task like "Thêm trang đăng nhập" doesn't waste
// keyword slots on "thêm" / "trang".
//
// Stdlib only — the TS port reached for `String.normalize("NFD")` +
// the combining-marks regex; the Go stdlib doesn't expose Unicode
// normalization, and the only stable third-party API for it is
// golang.org/x/text which the bridge doesn't pull in. So the strip
// pass below is a hand-rolled rune→ASCII table that covers the
// Vietnamese alphabet (where every character either has an NFD
// decomposition to ASCII + combining marks OR is the special đ/Đ pair)
// plus the core Latin-1 diacritics that show up in repo + capability
// names borrowed from European ecosystems. Coverage is intentionally
// narrow — a Cyrillic / CJK task body still tokenizes correctly,
// it just doesn't get folded.

import (
	"strings"
)

// diacriticMap folds every Vietnamese diacritic + the common Latin-1
// diacritics into their base ASCII letter. The list mirrors what the
// TS NFD pipeline produced — generated by walking the Vietnamese
// alphabet's a/e/i/o/u/y vowel table (each with five tone marks and
// optional circumflex / breve / horn) plus the d/D special case.
//
// Anything not in this map passes through untouched, so non-Latin
// scripts (Cyrillic, Greek, CJK) survive Tokenize unchanged — they
// just won't match the bilingual vocab tables.
var diacriticMap = map[rune]rune{
	// a / A — circumflex, breve, grave, acute, hook, tilde, dot-below,
	//         all combinations of (â/ă) × tone.
	'à': 'a', 'á': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a',
	'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
	'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
	'À': 'A', 'Á': 'A', 'Ả': 'A', 'Ã': 'A', 'Ạ': 'A',
	'Â': 'A', 'Ầ': 'A', 'Ấ': 'A', 'Ẩ': 'A', 'Ẫ': 'A', 'Ậ': 'A',
	'Ă': 'A', 'Ằ': 'A', 'Ắ': 'A', 'Ẳ': 'A', 'Ẵ': 'A', 'Ặ': 'A',
	// e / E
	'è': 'e', 'é': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e',
	'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
	'È': 'E', 'É': 'E', 'Ẻ': 'E', 'Ẽ': 'E', 'Ẹ': 'E',
	'Ê': 'E', 'Ề': 'E', 'Ế': 'E', 'Ể': 'E', 'Ễ': 'E', 'Ệ': 'E',
	// i / I
	'ì': 'i', 'í': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i',
	'Ì': 'I', 'Í': 'I', 'Ỉ': 'I', 'Ĩ': 'I', 'Ị': 'I',
	// o / O
	'ò': 'o', 'ó': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o',
	'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
	'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
	'Ò': 'O', 'Ó': 'O', 'Ỏ': 'O', 'Õ': 'O', 'Ọ': 'O',
	'Ô': 'O', 'Ồ': 'O', 'Ố': 'O', 'Ổ': 'O', 'Ỗ': 'O', 'Ộ': 'O',
	'Ơ': 'O', 'Ờ': 'O', 'Ớ': 'O', 'Ở': 'O', 'Ỡ': 'O', 'Ợ': 'O',
	// u / U
	'ù': 'u', 'ú': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u',
	'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
	'Ù': 'U', 'Ú': 'U', 'Ủ': 'U', 'Ũ': 'U', 'Ụ': 'U',
	'Ư': 'U', 'Ừ': 'U', 'Ứ': 'U', 'Ử': 'U', 'Ữ': 'U', 'Ự': 'U',
	// y / Y
	'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
	'Ỳ': 'Y', 'Ý': 'Y', 'Ỷ': 'Y', 'Ỹ': 'Y', 'Ỵ': 'Y',
	// d / D — Vietnamese đ/Đ.
	'đ': 'd', 'Đ': 'D',
	// Common Latin-1 fillers that show up in European repo / capability
	// names ("café", "naïve", "façade"). Not exhaustive — just enough
	// that operator-curated capability tags don't fall off the bilingual
	// match path.
	'ñ': 'n', 'Ñ': 'N',
	'ç': 'c', 'Ç': 'C',
	'ß': 's',
	'ä': 'a', 'ë': 'e', 'ï': 'i', 'ö': 'o', 'ü': 'u',
	'Ä': 'A', 'Ë': 'E', 'Ï': 'I', 'Ö': 'O', 'Ü': 'U',
}

// StripDiacritics folds Vietnamese (and other Latin-script) diacritics
// so "khóa" → "khoa", "đăng" → "dang". See diacriticMap for coverage.
func StripDiacritics(text string) string {
	if text == "" {
		return ""
	}
	// Quick ASCII-only fast path — the vast majority of strings the
	// detector sees are already pure ASCII (file paths, capability
	// tags), and skipping the rune walk + builder allocation makes a
	// measurable difference on a hot tokenize loop.
	if isASCII(text) {
		return text
	}
	var b strings.Builder
	b.Grow(len(text))
	for _, r := range text {
		if mapped, ok := diacriticMap[r]; ok {
			b.WriteRune(mapped)
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] > 0x7f {
			return false
		}
	}
	return true
}

// Stopwords is the bilingual filler set. Skip words that carry no
// signal in either language. Always check tokens AFTER StripDiacritics
// + lowercase, so we only need to list ASCII forms here.
var Stopwords = func() map[string]struct{} {
	words := []string{
		// English fillers
		"the", "and", "of", "to", "for", "with", "this", "that",
		"are", "be", "as", "or", "at", "from", "it", "its",
		"but", "not", "no", "so", "do", "does", "did", "done", "have",
		"has", "had", "will", "would", "should", "can", "could", "may", "might",
		"into", "out", "off", "over", "under", "than", "then", "when", "where",
		"what", "who", "how", "why", "all", "any", "some", "these", "those",
		// Vietnamese fillers (post-diacritic-strip).
		// NOTE: we do NOT include "dang" / "nhap" / "ky" / "hoc" here even
		// though some of them have filler senses — they're load-bearing in
		// the auth + lms feature vocab ("dang nhap" = login,
		// "khoa hoc" = course, "hoc vien" = student).
		"cua", "cho", "thi", "trong", "nay", "kia", "duoc",
		"neu", "nhu", "khi", "den", "voi", "boi",
		"khong", "chua", "moi", "ban", "minh", "toi",
		"anh", "chi", "ai", "nao", "sao", "vay",
		"rang", "phai", "muon", "len", "xuong", "vao",
		"qua", "lai", "luon", "van", "cung", "rat", "lam",
		// Action verbs (English)
		"add", "fix", "create", "make", "use", "remove",
		"delete", "change", "edit", "implement", "refactor", "review",
		"check", "verify", "ship", "deploy", "merge", "rebase", "update",
		// Action verbs (Vietnamese, post-diacritic-strip)
		"them", "sua", "xoa", "tao", "kiem", "tra",
		"trien", "khai", "viet", "doc", "chay", "thuc", "hien",
		"hoan", "thanh", "duyet",
		// Programming meta-words
		"task", "todo", "need", "needs", "want", "wants",
		"please", "function", "feature", "code", "file", "page", "trang",
		"src", "lib", "public", "dist",
		"tests", "spec", "specs", "config", "configs", "json",
		"tsx", "jsx", "mjs",
		"package", "lock", "readme", "license", "docs",
		"tinh", "nang", "chuc", "muc", "phan",
	}
	m := make(map[string]struct{}, len(words))
	for _, w := range words {
		m[w] = struct{}{}
	}
	return m
}()

// Tokenize turns free-form text into normalized lowercase tokens.
// Pipeline:
//  1. Lowercase
//  2. Strip Vietnamese diacritics (so "khóa học" matches "khoa hoc")
//  3. Split on non-alphanumeric runs
//  4. Drop tokens shorter than 3 chars, pure-numeric tokens, stopwords
//
// Returns deduped tokens in encounter order. Use this for ANY
// detection surface so all impls see the same vocabulary.
func Tokenize(text string) []string {
	if text == "" {
		return nil
	}
	normalized := StripDiacritics(strings.ToLower(text))
	seen := make(map[string]struct{})
	out := []string{}
	// Manual split rather than regexp: the splitter loop runs once per
	// task body and keeps the package off regexp for hot paths.
	start := -1
	flush := func(end int) {
		if start < 0 {
			return
		}
		tok := normalized[start:end]
		start = -1
		if len(tok) < 3 {
			return
		}
		if isAllDigits(tok) {
			return
		}
		if _, isStop := Stopwords[tok]; isStop {
			return
		}
		if _, dup := seen[tok]; dup {
			return
		}
		seen[tok] = struct{}{}
		out = append(out, tok)
	}
	for i := 0; i < len(normalized); i++ {
		c := normalized[i]
		isWord := (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')
		if isWord {
			if start < 0 {
				start = i
			}
		} else {
			flush(i)
		}
	}
	flush(len(normalized))
	return out
}

func isAllDigits(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// Bigrams returns adjacent bigram tokens from a tokenized list. Useful
// for matching multi-word features ("dang nhap" = "đăng nhập" =
// login). We only generate adjacent bigrams in the original token
// order — anything smarter would need real NLP.
func Bigrams(tokens []string) []string {
	if len(tokens) < 2 {
		return nil
	}
	out := make([]string, 0, len(tokens)-1)
	for i := 0; i+1 < len(tokens); i++ {
		out = append(out, tokens[i]+" "+tokens[i+1])
	}
	return out
}

// CountMatches counts occurrences of `needle` in `haystack` after both
// have been normalized via the same pipeline (lowercase + diacritic-
// strip). Stopwords are NOT filtered here — needles may legitimately
// be stopwords (e.g. profile keywords). Caller decides relevance.
func CountMatches(haystack, needle string) int {
	if needle == "" {
		return 0
	}
	h := StripDiacritics(strings.ToLower(haystack))
	n := StripDiacritics(strings.ToLower(needle))
	if n == "" {
		return 0
	}
	count := 0
	from := 0
	for {
		idx := strings.Index(h[from:], n)
		if idx == -1 {
			break
		}
		count++
		from += idx + len(n)
	}
	return count
}
